<?php

namespace AppBundle\Repository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPayments()
    {
        $qb = $this->createQueryBuilder('payment')
            ->innerJoin('payment.user', 'user')
            ->select(['payment'])
            ->orderBy('payment.paymentDate', 'desc');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
